name: 'Changelog'
description: 'Generate changelog with git-chglog'
inputs:
  path:
    description: 'Filter commits only to this path'
    required: true
  tag:
    description: 'Tag version to generate changelog'
    required: true
outputs:
  changelog:
    description: 'The content of the changelog'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.tag }}
