# Default values for metaapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

helloWorld:
  repository: local/hello-world
  pullPolicy: IfNotPresent
  tag: 0.0.1

byebyeWorld:
  repository: local/byebye-world
  pullPolicy: IfNotPresent
  tag: 0.0.2

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
