replicaCount: 1
helloWorld:
  repository: local/hello-world
  pullPolicy: IfNotPresent
  tag: hello-v0.107.1
byebyeWorld:
  repository: local/byebye-world
  pullPolicy: IfNotPresent
  tag: byebye-v0.11.0
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
