# Value file for metaap
replicaCount: 1
app:
  repository: local/app
  pullPolicy: IfNotPresent
  tag: v0.4.0
helloWorld:
  repository: local/hello-world
  pullPolicy: IfNotPresent
  tag: v0.134.0
byebyeWorld:
  repository: local/byebye-world
  pullPolicy: IfNotPresent
  tag: v0.19.0
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
