name: 'action-monorepo-version-tags-lifecycle'
description: 'Generate version tags on a monorepo with multiple components'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  dry-run:
    description: 'Enable dry run mode, expected "true" "false"'
    required: false
    default: 'false'

outputs:
  tag:
    description: 'The new version tag that was created'
runs:
  using: 'node12'
  main: 'dist/index.js'
