# Build and publish the docker image for component Hello
# Executed on 'hello-v*.*.*' tags

name: 3. Hello Build and Publish

on:
  push:
    tags:
      - 'hello-v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PATNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub Registry
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output
        id: version
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo Version for new release: ${GITHUB_REF#refs/*/}

      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./hello-world
      #    file: ./hello-world/Dockerfile
      #    platforms: linux/amd64
      #    push: true
      #    tags: |
      #      konstellation/hello-world:${{ steps.version.outputs.tag }}
      #      konstellation/hello-world:latest
