name: ByeBye Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"

jobs:
  build:
    uses: intelygenz/monorepo-ci-cd-poc/.github/actions/components-build.yml@${{ github.sha }}
    with:
      component: "byebye"
