name: ByeBye Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"

jobs:
  build:
    uses: ./.github/workflows/components-build.yml
    with:
      component: "byebye"
