name: Release

on:
  push:
    branches: ["main"]
    paths:
      - "byebye-world/**/*"

jobs:
  release-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a release
        uses: ./.github/actions/product-version-tags
        with:
          prefix: "byebye-"
          mode: 'release'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
