name: ByeBye Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"


env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}


jobs:

  quality-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"

      - name: flake8 Lint
        uses: py-actions/flake8@v1


  create-release-tag:
    if: github.ref == 'refs/heads/main' # only in main branch
    needs: quality-checks
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.release_tag.outputs.tag }}
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Generate a release tag
        uses: ./.github/actions
        id: release_tag
        with:
          mode: 'component'
          type: 'final'
          component-prefix: "byebye-"


  create-fix-tag:
    if: startsWith(github.ref, 'refs/heads/release') # only in release branches
    needs: quality-checks
    runs-on: ubuntu-20.04
    outputs:
       tag: ${{ steps.fix_tag.outputs.tag }}
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - uses: chrisdickinson/setup-yq@latest
      - name: Get component versions
        id: component_version
        run: |
          TAG=`yq r metaapp/values.yaml 'byebyeWorld.tag'`
          echo ::set-output name=TAG::${TAG}
          echo Component version in release branch is ${TAG}

      - name: Generate a fix
        uses: ./.github/actions
        id: fix_tag
        with:
          mode: 'component'
          type: 'fix'
          component-prefix: "byebye-"
          current-tag: ${{ steps.component_version.outputs.TAG }}


  build-release:
    if: |
      always() &&
      (needs.create-release-tag.outputs.tag || needs.create-fix-tag.outputs.tag)
    needs: [create-release-tag, create-fix-tag]
    runs-on: ubuntu-latest
    steps:
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub Registry
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Store fix tag
        run: echo Tag set to ${{needs.create-release-tag.outputs.tag}}${{needs.create-fix-tag.outputs.tag}}

      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./byebye-world
      #    file: ./byebye-world/Dockerfile
      #    platforms: linux/amd64
      #    push: true
      #    tags: |
      #      konstellation/byebye-world:${{ steps.version.outputs.tag }}
      #      konstellation/byebye-world:latest

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
