# Generates a release tag for component ByeBye
# Executed only on main and if the "ByeBye Quality" completes successfully
# Generates a tag with 'byebye-v*.*.0'

name: ByeBye Release

on:
  workflow_run:
    workflows:
      - "ByeBye Quality"
    branches: [main]
    types:
      - completed

jobs:
  release-component:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://github.community/t/workflow-run-success-type-reference/133194/3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a release
        uses: ./.github/actions
        with:
          prefix: "byebye-"
          mode: 'component-release'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
