name: ByeBye Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "byebye-world/**/*"
      - ".github/byebye-quality*"

jobs:
  quality_checks:
    uses: konstellation-io/github-workflows/.github/workflows/quality-checks-python.yaml@main

