# Generates a release tag for component Hello
# Executed only on main and if the "Hello Quality" completes successfully
# Generates a tag with 'hello-v*.*.0'

name: 2. Hello Tag Release

on:
  workflow_run:
    workflows:
      - "Hello Quality"
    branches: [main]
    types:
      - completed

jobs:
  release-component:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://github.community/t/workflow-run-success-type-reference/133194/3
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Generate a release tag
        uses: ./.github/actions
        with:
          prefix: "hello-"
          mode: 'component-release'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
