name: Hello Build and Publish

on:
  push:
    tags:
      - 'hello-v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      #- name: Login to DockerHub Registry
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Component Version
        id: version
        uses: ./.github/actions
        with:
          prefix: "hello-"
          mode: 'component-get-last-version'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}

      - name: Display the component version
        run: echo "Build & Release component hello with version ${{ steps.version.outputs.tag }}"

      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./hello-world
      #    file: ./hello-world/Dockerfile
      #    platforms: linux/amd64
      #    push: true
      #    tags: |
      #      konstellation/hello-world:${{ steps.get_version.outputs.VERSION }}
      #      konstellation/hello-world:latest
