name: Hello Component Build

on:
  push:
    tags-ignore:
      - "**"
    paths:
      - "hello-world/**/*"
      - ".github/hello-quality*"


env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}


jobs:

  quality-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "2.7"

      - name: flake8 Lint
        uses: py-actions/flake8@v1
