name: Hello Release

on:
  push:
    branches: ["main"]
    paths:
      - "hello-world/**/*"

jobs:
  release-component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a release
        uses: ./.github/actions
        with:
          prefix: "hello-"
          mode: 'component-release'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
