# Generates a fix tag for component Hello
# Executed only on main and if the "Hello Quality" completes successfully
# Generates a tag with 'hello-vX.X.*'

name: 7. Hello Component Fix

on:
  workflow_run:
    workflows:
      - "1. Hello Quality"
    branches: ["release/*"]
    types:
      - completed

jobs:
  create-fix:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://github.community/t/workflow-run-success-type-reference/133194/3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }} # Checkout the branch in the original workflow

      - uses: chrisdickinson/setup-yq@latest
      - name: Get component versions
        id: compoment_version
        run: |
          TAG=`yq r metaapp/values.yaml 'helloWorld.tag'`
          echo ::set-output name=TAG::${TAG}
          echo Component version in release branch is ${TAG}

      - name: Generate a fix
        uses: ./.github/actions
        with:
          prefix: "hello-"
          current-version: ${{ steps.compoment_version.outputs.TAG }}
          mode: 'component-fix'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}

