name: Hello Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "hello-world/**/*"
      - ".github/hello-quality*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "hello-world/**/*"
      - ".github/hello-quality*"


jobs:
  build:
    uses: intelygenz/monorepo-ci-cd-poc/.github/workflows/components-build.yml@feature/hello-1
    with:
      component: "hello"
      github_token: ${{ secrets.PATNAME }}
