name: Helm Pre Release

on:
  workflow_run:
    workflows:
      - "Hello Build and Publish"
      - "ByeBye Build and Publish"
    types:
      - completed

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    # if needed for checking workflow success: https://github.community/t/workflow-run-success-type-reference/133194/2
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: ./.github/actions
        with:
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'rc'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
