name: Helm Release

on:
  workflow_run:
    workflows:
      - "Hello Component Build"
      - "ByeBye Component Build"
    types:
      - completed
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*-rc.*'
    branches: ["release/*"]


env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}


jobs:

  generate-prerelease:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.ref == 'ref/head/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: ./.github/actions
        with:
          current-major: 0
          prefix: "release/v"
          mode: 'pre-release'
          pre-release: 'rc'
          default-branch: 'main'

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello Component Version
        id: hello_version
        uses: ./.github/actions
        with:
          prefix: "hello-"
          mode: 'component-get-last-version'

      - name: ByeBye Component Version
        id: byebye_version
        uses: ./.github/actions
        with:
          prefix: "byebye-"
          mode: 'component-get-last-version'

      - name: App Version
        id: get_version
        run: |
          # format version X.X.X
          RELEASE_VERSION=`echo "${GITHUB_REF#refs/tags/}" | sed -e 's/v//g' | sed -e 's/-rc.*/.0/g'`
          echo ::set-output name=RELEASE_VERSION::${RELEASE_VERSION}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: chrisdickinson/setup-yq@latest
      - name: Replace component versions
        run: |
          # set image tags on kdl
          yq w -i metaapp/values.yaml 'helloWorld.tag' ${{ steps.hello_version.outputs.tag }}
          yq w -i metaapp/values.yaml 'byebyeWorld.tag' ${{ steps.byebye_version.outputs.tag }}

          # set app version and chart version for kdl
          yq w -i metaapp/Chart.yaml 'appVersion' --style=double ${{ steps.get_version.outputs.VERSION }}
          yq w -i metaapp/Chart.yaml 'version' ${{ steps.get_version.outputs.RELEASE_VERSION }}

          # debug output
          echo 'helloWorld.tag' ${{ steps.hello_version.outputs.tag }}
          echo 'byebyeWorld.tag' ${{ steps.byebye_version.outputs.tag }}
          echo 'appVersion' ${{ steps.get_version.outputs.VERSION }}
          echo 'version' ${{ steps.get_version.outputs.RELEASE_VERSION }}

      - name: Commit files
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Update chart to version ${{ steps.get_version.outputs.RELEASE_VERSION }} [skip-ci]" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: main

  create-fix:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'ref/head/release')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: chrisdickinson/setup-yq@latest
      - name: Get component versions
        id: compoment_version
        run: |
          TAG=`yq r metaapp/values.yaml 'helloWorld.tag'`
          echo ::set-output name=TAG::${TAG}
          echo Component version in release branch is ${TAG}

      - name: Generate a fix
        uses: ./.github/actions
        with:
          prefix: "hello-"
          current-version: ${{ steps.compoment_version.outputs.TAG }}
          mode: 'component-fix'
