# Creates a release branch and tag for helm chart
# Executed manually
# Generate a branch with name 'release/v*.*' tag with 'v*.*.0'

name: 5. Helm New Release

on:
  workflow_dispatch:

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: ./.github/actions
        with:
          prefix: "release/"
          mode: 'release'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
