# Generate a new version of the helm chart updating the components to their respective lasts version
# Executed on 'v*.*.*' and 'v*.*-rc.*' tags
# This workflow updates the helm chart file Chart.yml and values.yml with new versions and commit them

name: 6. Helm Release Fix

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*-rc.*'

jobs:
  set-pre-release-mode:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://github.community/t/workflow-run-success-type-reference/133194/3
    steps:
      - name: Get Tag Patch
        run: |
          # Get the patch number for the tag that triggered the workflow
          patch=`echo "${GITHUB_REF#refs/tags/}" | awk 'BEGIN { FS = "." } ; { print $3}'`
          echo ::set-env name=PATCH_NUMBER::patch
          echo Patch number found is ${patch}

  generate-prerelease-fix:
    runs-on: ubuntu-latest
    needs: set-pre-release-mode
    if: ${{ env.PATCH_NUMBER != 0 }} # runs only for fixes pre-releases
    steps:
      - name: Get Branch for tag
        id: get_branch
        run: |
          raw=$(git branch -r --contains ${{ GITHUB_REF#refs/tags/ }})
          branch=${raw/origin\/}
          echo ::set-output name=BRANCH::$branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_branch.output.BRANCH }}

      - uses: chrisdickinson/setup-yq@latest
      - name: Get release versions
        id: get_release_version
        run: |
          CHART_VERSION=`yq r metaapp/Chart.yaml 'version'`
          echo ::set-output name=CHART_VERSION::${CHART_VERSION}
          echo Component version in release branch is ${CHART_VERSION}
