# Generate a new version of the helm chart updating the components to their respective lasts version
# Executed on 'v*.*.*' and 'v*.*-rc.*' tags
# This workflow updates the helm chart file Chart.yml and values.yml with new versions and commit them

name: 6. Helm Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*-rc.*'

jobs:

  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PATNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello Component Version
        id: hello_version
        uses: ./.github/actions
        with:
          prefix: "hello-"
          mode: 'component-get-last-version'

      - name: ByeBye Component Version
        id: byebye_version
        uses: ./.github/actions
        with:
          prefix: "byebye-"
          mode: 'component-get-last-version'

      - name: App Version
        id: get_version
        run: |
          # format version X.X.X
          RELEASE_VERSION=`echo "${GITHUB_REF#refs/tags/}" | sed -e 's/v//g' | sed -e 's/-rc.*/.0/g'`
          echo ::set-output name=RELEASE_VERSION::${RELEASE_VERSION}
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - uses: chrisdickinson/setup-yq@latest
      - name: Replace component versions
        run: |
          # set image tags on kdl
          yq w -i metaapp/values.yaml 'helloWorld.tag' ${{ steps.hello_version.outputs.tag }}
          yq w -i metaapp/values.yaml 'byebyeWorld.tag' ${{ steps.byebye_version.outputs.tag }}

          # set app version and chart version for kdl
          yq w -i metaapp/Chart.yaml 'appVersion' \"${{ steps.get_version.outputs.VERSION }}\"
          yq w -i metaapp/Chart.yaml 'version' ${{ steps.get_version.outputs.RELEASE_VERSION }}

          # debug output
          echo 'helloWorld.tag' ${{ steps.hello_version.outputs.tag }}
          echo 'byebyeWorld.tag' ${{ steps.byebye_version.outputs.tag }}
          echo 'appVersion' ${{ steps.get_version.outputs.VERSION }}
          echo 'version' ${{ steps.get_version.outputs.RELEASE_VERSION }}

      - name: Commit files
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Update chart to version ${{ steps.get_version.outputs.RELEASE_VERSION }} [skip-ci]" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PATNAME }}
          branch: main
