# Creates a pre-release tag for helm chart. A new pre-release of the chart is created when a component is updated.
# Executed only when a Quality* workflow completes successfully
# Generate a tag with 'v*.*-rc.*'

name: Helm Pre Release

on:
  workflow_run:
    workflows:
      - "Hello Build and Publish"
      - "ByeBye Build and Publish"
    types:
      - completed

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # https://github.community/t/workflow-run-success-type-reference/133194/3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: ./.github/actions
        with:
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'rc'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
