name: Helm Pre Release

on:
  workflow_run:
    workflows:
      - "Hello Build and Publish"
      - "ByeBye Build and Publish"
    types:
      - completed

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: intelygenz/action-product-version-tags@v0.1.8
        with:
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'rc'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
