# This workflow is responsible for releasing the helm chart:
# - Updates the version attribute in the Chart.yml file
# - Commit the changes
# - Creates a new product tag for the release

name: Helm Release

on:
  workflow_run:
    workflows:
      - "Hello Component Build"
      - "ByeBye Component Build"
      - "App Application Build"
    types:
      - completed


env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}


jobs:

  calculate-rc-tag:
    # Just after a workflow completes successfully and the workflows was triggered in main branch
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.rc_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a pre-release
        id: rc_tag
        uses: ./.github/actions
        with:
          current-major: 0
          mode: 'product'
          type: 'pre-release'
          release-branch-prefix: "release/v"
          pre-release-name: 'rc'
          update-versions-in: '[{"file": "metaapp/Chart.yaml", "property": "version"}]'


  calculate-fix-tag:
    # Just after a workflow completes successfully and the workflows was triggered in a release branch
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'release')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fix_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a fix tag
        id: fix_tag
        uses: ./.github/actions
        with:
          mode: 'product'
          type: 'fix'
          release-branch-prefix: "release/v"
          update-versions-in: '[{"file": "metaapp/Chart.yaml", "property": "version"}]'
