name: New Release Branch

on:
  workflow_dispatch:

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a release
        uses: ./.github/actions
        with:
          prefix: "release/v"
          mode: 'release-branch'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
