name: Helm Release

on:
  workflow_run:
    workflows:
      - "Hello Component Build"
      - "ByeBye Component Build"
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}


jobs:

  calculate-rc-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo Calculate rc tag


  release:
    needs: calculate-rc-tag
    runs-on: ubuntu-latest
    steps:
      - run: echo Release


  test:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo Test after release