apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metaapp.fullname" . }}
  labels:
    app.kubernetes.io/name: metaapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: metaapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metaapp
    spec:
      containers:
        - name: hello-world
          image: "{{ .Values.helloWorld.repository }}:{{ .Values.helloWorld.tag }}"
          imagePullPolicy: {{ .Values.helloWorld.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        - name: byebye-world
          image: "{{ .Values.byebyeWorld.repository }}:{{ .Values.byebyeWorld.tag }}"
          imagePullPolicy: {{ .Values.byebyeWorld.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP