apiVersion: v1
kind: Service
metadata:
  name: {{ include "metaapp.fullname" . }}
  labels:
    app.kubernetes.io/name: metaapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: hello
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: byebye
  selector:
    app.kubernetes.io/name: metaapp
